chore: change fixed L2 names in gui to L2/3
jonescompneurolab/hnn-core pull request #907
Opened 2024-10-18 17:45 UTC by asoplata

Note that this does not change the L2 names inherent in the `cell_types` which are loaded dynamically in the gui, such as shown here: https://github.com/jonescompneurolab/hnn-core/issues/904#issue-2589984642

2024-10-18 18:40 UTC, jasmainak commented
merge button is yours @gtdang and @ntolley

2024-10-18 18:40 UTC, jasmainak commented on hnn_core/gui/gui.py
> +            options=['L2/3 Pyramidal', 'L5 Pyramidal'],
don't forget to update whats_new.rst so you can be credited in the next release

2024-10-18 22:09 UTC, gtdang requested changes
Ooo this isn't going to be quite a simple change. There are several keys that are constructed that rely on the radio button titles, which will dynamically update viewable parameters. Let's talk Monday.

2024-10-21 21:21 UTC, asoplata commented
@gtdang I think I found where a simple string replace lets the read-in text in `cell_type` play well with `cell_parameters_key`. I tested it in the GUI and it seems to correctly load the properties, and switch between them.

2024-10-22 21:41 UTC, gtdang approved these changes
Approved

2024-10-22 21:42 UTC, merged

2024-10-23 13:23 UTC, asoplata commented
Resolves #904